### ISSUE TITLE
bash file semaphore script - is the script needed?

### ISSUE THREAD

**Issue by nhosoi** [linux-system-roles/kdump#130]
Hello, we are trying to clean up the `shellcheck` github action if a role has no shell script in it: [Remove shellcheck github action](https://github.com/linux-system-roles/kdump/pull/129).

I've noticed there is a script `semaphore` in the role's top dir.
```
commit f4c6ad01cb82223ae1794a4ebe6feec664822057
Author: Lars Karlitski <lars@karlitski.net>
Date:   Wed Apr 26 11:19:26 2017 +0200
    test: add semaphore script    
    This script can be used on sempahoreci.com. Put it here instead of on
    sempahore so that it is versioned with the repository and so that we can
    change it on branches.
```
May I ask if the script is still valid and used? If so, how? The script calls `run-tests.sh` in it and I cannot find the file in the `kdump` repo.

If it is being used, I'm going to add `differential-shellcheck.yml` to the github action. If it is not, can we remove `semaphore`? >> @richm

**Comment by richm** [comment]
Yes, please remove it.

**Comment by nhosoi** [comment]
> Yes, please remove it.

Thanks!
