### ISSUE TITLE
`default` option has been renamed to `failure_action`

### ISSUE THREAD

**Issue by jelly** [linux-system-roles/kdump#154]
On Fedora 38, this (for now) harmless warning appears.

```
kdump: warning: option 'default' was renamed 'failure_action' and will be removed in the future.
please update /etc/kdump.conf to use option 'failure_action' instead.
```

**Comment by licliu** [comment]
`default` should be removed in the future, but for compatibility reasons, we will not deprecate the default option yet, on Fedora and RHEL9 and later systems using `failure_action` is better but not required.
