### ISSUE TITLE
'main' version breaks ansible-galaxy install

### ISSUE THREAD

**Issue by oebeledrijfhout** [linux-system-roles/kdump#181]
Version 'main'  was published to Ansible Galaxy and this breaks installing without specifying a version:

$ ansible-galaxy install linux-system-roles.kdump
Starting galaxy role install process
- downloading role 'kdump', owned by linux-system-roles
[WARNING]: - linux-system-roles.kdump was NOT installed successfully: Unable to
compare role versions (0.1, 1.0.0, 1.0.0-rc.1, 1.0.1, 1.0.2, 1.0.3, 1.0.4,
1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6,
1.2.7, 1.2.8, 1.2.9, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7,
1.3.8, main) to determine the most recent version due to incompatible version
formats. Please contact the role author to resolve versioning conflicts, or
specify an explicit role version to install.
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.

**Comment by richm** [comment]
Waiting for the fix to be deployed in galaxy - https://github.com/ansible/galaxy_ng/pull/1946
