### ISSUE TITLE
Proposal to change the dump_target "kind" option

### ISSUE THREAD

**Issue by tabowling** [linux-system-roles/kdump#2]
I would like to propose that we change the "kind" option to either "type" or "method".  

In the docs, there is no clear term used for this.  In English, "kind" relatively clear about its intention but it sounds awkward.  I think "type" would probably work the best.

References:
/usr/share/doc/kexec-tools-2.0.7/supported-kdump-targets.txt
man kdump.conf

**Comment by larskarlitski** [comment]
I agree. I've opened #5 which renames it to `type`.
