### ISSUE TITLE
Proposal for default core_collector value

### ISSUE THREAD

**Issue by tabowling** [linux-system-roles/kdump#7]
I propose that the core_collector variable should have a default value that matches the default value in the /etc/kdump.conf file provided by kexec-tools package.

`core_collector: "makedumpfile -l --message-level 1 -d 31"`

**Comment by larskarlitski** [comment]
I thought it already did that when no value is given? The [documentation](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Deployment_Guide/s2-kdump-configuration-cli.html) is a bit unclear about that.

**Comment by richm** [comment]
I don't think we need this anymore - if we do, please reopen with additional information
