### ISSUE TITLE
Question: Is this role compatible to SLES (15)?

### ISSUE THREAD

**Issue by heiwu** [linux-system-roles/kdump#94]
Hi all, i'm curious how to set up kdump on our SLES15 systems and found this role that might be handy for us.
Is there any information about compatibility / known issues when using this role on SLES systems?
At [line 22 in tasks/main.yml](https://github.com/linux-system-roles/kdump/blob/d002a7b817df67c8d110c89e53e84b4847e4dd12/tasks/main.yml#L22) you are working on kdump.conf which does not exist on our Systems, and i'd really like to know which issues this might bring up in future.
BR Heiner

**Comment by richm** [comment]
> Hi all, i'm curious how to set up kdump on our SLES15 systems and found this role that might be handy for us. Is there any information about compatibility / known issues when using this role on SLES systems? At [line 22 in tasks/main.yml](https://github.com/linux-system-roles/kdump/blob/d002a7b817df67c8d110c89e53e84b4847e4dd12/tasks/main.yml#L22) you are working on kdump.conf which does not exist on our Systems, and i'd really like to know which issues this might bring up in future. BR Heiner

I'm assuming this role won't work with sles - it hasn't been developed for sles, nor has it been tested with sles.  Patches welcome.

**Comment by spetrosi** [comment]
> At [line 22 in tasks/main.yml](https://github.com/linux-system-roles/kdump/blob/d002a7b817df67c8d110c89e53e84b4847e4dd12/tasks/main.yml#L22) you are working on kdump.conf which does not exist on our Systems, and i'd really like to know which issues this might bring up in future. BR Heiner

kdump.conf would be provided by the package that provides kdump. In RHEL and Fedora, it's provided by the kexec-tools RPM. I do not what provides it for SLES.

**Comment by heiwu** [comment]
> kdump.conf would be provided by the package that provides kdump. In RHEL and Fedora, it's provided by the kexec-tools RPM. I do not what provides it for SLES.

Seems to be different in SLES: 
```
# rpm -ql kexec-tools |grep '/etc/kdump'
# rpm -ql kdump* |grep '/etc/kdump'
#
# rpm -qa|grep -e kdump
kdump-0.9.0-11.6.1.x86_64
yast2-kdump-4.2.9-1.79.x86_64
#
```
